### PR TITLE
Add "pt_BR" translation files.

### PR DESCRIPTION
**Pull request by allysonbarros**
@aitormagan I closed the other PR and opened this pointing to `develop` branch adding the .po e .mo files.

### CODE REVIEW

**Comment by aitormagan** [comment]
Thank you so much for your translation. I have already merged it. :)

P.S.: I appreciate so much the `gitignore` changes to avoid MacOS files 👍

**Comment by aitormagan** [comment]
P.S.2: I have renamed the files in order the translation to work: they don't work as you have committed them. The name of the files must be `pt_BR/LC_MESSAGES/ckanext-datarequests.(po|mo)`. 

BR
Aitor

**Comment by allysonbarros** [comment]
@aitormagan thanks! 👍

**Comment by aitormagan** [comment]
Version `0.4.1` with your translation has been released. You can find it in PyPi! 😄

**Pull request merged**
