### PR TITLE
Added Romanian Translations

### PR DESCRIPTION
**Pull request by costibleotu**
First of all, thank you for this great CKAN extension.

I've created the Romanian translations

### CODE REVIEW

**Comment by aitormagan** [comment]
Hi! Thank you so much for your contribution to this repo! However, in order to accept translations, the `.mo` file is also required :).

**Comment by costibleotu** [comment]
Then we should remove the `.mo` from `.gitignore` :)

**Comment by aitormagan** [comment]
Done! That explained why all the translations came without the `.mo` file. Please, try to include it now. I would generate it for you, but I don't have the environment to do so :(

**Comment by costibleotu** [comment]
I pushed  the `.mo` now

**Comment by aitormagan** [comment]
Merged :)

**Pull request merged**
