### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by kvlahrosch**
Hi Aitor,

we are going to use ckanext-datarequests for the new version of our CKAN-based open data portal and thus needed a German translation for it. Well, here it is, would you like to merge it into the main ckanext-datarequests repository?

Thank you very much

Sebastian

### CODE REVIEW

**Comment by aitormagan** [comment]
Hi,

Thank you so much for your contribution. I will be glad to merge your pull request but I need some changes before doing it. I need you to compile the `po` file in order to get the `mo` file. Without it, the translation won't work in other systems. I would do it, but currently I don't have the environment to do so :(. So please, commit the `mo` file if you can.

You can generate the `mo` file by running:

```
python setup.py compile_catalog
```

Once the commit is pushed, I will merge your PR and generate a new release so you can install the latest version with the German translation.

Thank you so much!
Aitor

**Comment by kvlahrosch** [comment]
Dear Aitor,

it was a pleasure to contribute to ckanext-datarequests – thank _you_ for that wonderful software! I commited the `mo` you requested in [this commit](https://github.com/conwetlab/ckanext-datarequests/pull/25/commits/cc613028717f63b62e1ac5b45772bd759f5ba015).

Thank you very much
Sebastian

**Comment by aitormagan** [comment]
Thank you so much! I will try to merge your PR as soon as possible! :)

**Comment by aitormagan** [comment]
Hi @kvlahrosch,

I can see that you have included extra changes in the PR apart for the ones intended for the translation. Do you want me to merge them? Take into account that the changes you have included ensure the compatibility with CKAN 2.7, but I have to check if those changes work properly in previous versions.

Best regards.

**Comment by kvlahrosch** [comment]
Hi Aitor,

you can exclude my extra changes starting with [this commit](https://github.com/rostock/ckanext-datarequests/commit/e1f62d475957ee0e996bc76aeb164ef8a1c43943): they for sure won't work out of the box with CKAN <= 2.6x. Obviously, once you opened a pull request on a branch, GitHub automatically adds all subsequent commits to that branch to the pull request. I didn't have that in mind.

Best regards

Sebastian

**Comment by aitormagan** [comment]
I have merge your changes into the develop branch! As soon I have tested the translation is working properly I will publish the `0.3.3` release which will include the German translation.

Thank you for your cooperation.

**Comment by aitormagan** [comment]
Hi @kvlahrosch ,

I have been checking the translation but I think that something is not OK (sorry, but I do not speak German). The translation for "Closed" is "Status". Is that correct? 

BR
Aitor

**Comment by kvlahrosch** [comment]
Hi Aitor,

wow that you stumbled on that mistake of mine translating "Closed" with "Status" in the first place. Apart from that, there were a few other mistakes, so I pushed [this commit](https://github.com/rostock/ckanext-datarequests/commit/6e549d787d7581e3d8ad0926b7ad32a8785cd9db) which bugfixes the German translation. Maybe you can cherry-pick the translation part of that commit and leave out the rest.

Best wishes

Sebastian

**Comment by aitormagan** [comment]
Hi Sebastian,

As some of my workmates say, I am very strict validating code :)). I'm glad you have already correct the issues. I have included them in the `develop` branch. 

I haven't been able to cherry pick the commit you mentioned this commit also includes another changes. I have extracted the `mo` and `po` file from the commit and commited them to the `develop` branch, but I appear as the commiter. Anyway, I have included you in the Changelog and you appear as commiter of previous commits :)))

I don't want to say goodbye without thanking you for sharing the german translation of the extension. 

BR
Aitor

**Comment by kvlahrosch** [comment]
Hi Aitor,

thank you so much, it was a pleasure for me to contribute to ckanext-datarequests!

Best wishes

Sebastian

**Pull request closed without merging**
