### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by SimuliChina**
[i18n]: New language added: so

### CODE REVIEW

**Comment by aitormagan** [comment]
Hi!

First of all I want to thank you for your contribution. However, I am afraid I cannot accept this PR as we also need the `.mo` file which you can obtain following the instructions given in the README file.

Please, submit that file and we will study the PR :)

BR,
Aitor

**Comment by SimuliChina** [comment]
Hi,

I updated the pull request and added the `mo` file.

Thanks

**Comment by aitormagan** [comment]
Sorry, but I can’t see your new commit :( 

BR
Aitor

**Comment by SimuliChina** [comment]
I squashed it into the other commit.

**Comment by aitormagan** [comment]
Ok! I have just checked the mail and I didn't see a new commit so that's why asked. I have merged your contribution. Thank you so much!! :)

BR
Aitor

**Pull request merged**
